baseURL: "https://ynikl.github.io/"
title: 潜水员的咖啡小屋
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

profileMode:
  enabled: false # needs to be explicitly set

# 中间右上方 标题栏
menu:
  main:
    - identifier: blog
      name: blog
      url: /blog/
      weight: 1
    - identifier: books
      name: books
      url: /books/
      weight: 2
    - identifier: posts
      name: posts
      url: /posts/
      weight: 3
    - identifier: tags
      name: tags
      url: /tags/
      weight: 99
    - identifier: about
      name: me?
      url: /me/
      weight: 100
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true

markup:
    highlight:
        # anchorLineNos: true
        codeFences: true
        guessSyntax: true
        lineNos: true
        style: monokai

