title: 潜水员的咖啡小屋
description: "发发牢骚"
keywords: [Blog, Books, Posts]
author: 潜水员
# author: ["Me", "You"] # multiple authors
images: ["<link or path of image for opengraph, twitter-cards>"]
DateFormat: "January 2, 2006"
defaultTheme: auto # dark, light
disableThemeToggle: false

ShowFullTextinRSS: true
ShowReadingTime: true
ShowShareButtons: false
ShowPostNavLinks:  true
ShowBreadCrumbs: true
ShowCodeCopyButtons: true
disableSpecial1stPost: false
disableScrollToTop: false
comments: true
hidemeta: false
hideSummary: false
showtoc: false
tocopen: false

assets:
  # disableHLJS: true # to disable highlight.js
  # disableFingerprinting: true
  favicon: "/apple-touch-icon.png"
  favicon16x16: "<link / abs url>"
  favicon32x32: "<link / abs url>"
  apple_touch_icon: "/apple-touch-icon.png"
  safari_pinned_tab: "<link / abs url>"

label:
  text: "Home"
  icon: /apple-touch-icon.png
  iconHeight: 35

# profile-mode
profileMode:
  enabled: false # needs to be explicitly set
  title: ExampleSite
  subtitle: "This is subtitle"
  imageUrl: "<img location>"
  imageWidth: 120
  imageHeight: 120
  imageTitle: my image
  buttons:
    - name: Posts
      url: posts
    - name: Tags
      url: tags

# home-info mode
homeInfoParams:
  Title: "Hi there \U0001F44B"
  Content: Welcome to my blog

socialIcons:
  - name: "rss"
    url: "https://ynikl.github.io/index.xml"
  - name: twitter
    url: "https://twitter.com/k35402"
  - name: stackoverflow
    url: "https://stackoverflow.com/users/12519166/gilfoyle"
  - name: github
    url: "https://github.com/ynikl"
  - name: other
    url: "https://www.douban.com/people/ynikl/"

# analytics:
#   google:
#     SiteVerificationTag: "XYZabc"
#   bing:
#     SiteVerificationTag: "XYZabc"
#   yandex:
#     SiteVerificationTag: "XYZabc"

cover:
  hidden: true # hide everywhere but not in structured data
  hiddenInList: true # hide on list pages and home
  hiddenInSingle: true # hide on single page

editPost:
  URL: "https://github.com/ynikl/ynikl.github.io/tree/main/content"
  Text: "Suggest Changes" # edit text
  appendFilePath: true # to append file path to Edit link

# for search
# https://fusejs.io/api/options.html
fuseOpts:
  isCaseSensitive: false
  shouldSort: true
  location: 0
  distance: 1000
  threshold: 0.4
  minMatchCharLength: 0
  keys: ["title", "permalink", "summary", "content"]

# homepage - list
mainSections:
  - books
  - blog
  - posts
